on: 
  push:
    branches:
      - main

  schedule:
    - cron: 7 0 * * 1-5

  # run manually
  workflow_dispatch:

env:
  container_registry: ghcr.io/rajbos/actions-marketplace

jobs:
  get-action-data:
    runs-on: ubuntu-latest
    container: ghcr.io/rajbos/actions-marketplace/powershell:7 # ${{ env.container_registry }} doesn't work :-

    steps:
    - uses: actions/checkout@v2

    - id: update_step
      shell: pwsh
      name: Get action data
      run: | 
        $updateResult = (.\src\updater.ps1 -orgName ${{ github.repository_owner }} -PAT ${{ secrets.GITHUB_TOKEN }} -marketplaceRepo ${{ github.repository }} -userName "${{ secrets.username }}" -userEmail "${{ secrets.useremail }}" )
