on: 
  push:
    branches:
      - main
      - actions-update

  schedule:
    - cron: 7 0 * * 1-5

  # run manually
  workflow_dispatch:

env:
  container_registry: ghcr.io/rajbos/actions-marketplace

jobs:
  get-action-data:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: rajbos/github-action-load-available-actions@typescript
      name: load available actions
      id: load-actions
      with: 
        PAT: ${{ secrets.PAT }}
        user: ${{ github.repository_owner }}

    - shell: pwsh
      name: Store json file
      run: echo '${{ steps.load-actions.outputs.actions }}' > 'actions-data.json'
          
    - name: Upload result file as artefact
      uses: actions/upload-artifact@v2
      with: 
        name: actions
        path: actions-data.json

    # store in current repo, but in a separate branch

    # - id: update_step
    #   shell: pwsh
    #   name: Get action data
    #   run: | 
    #     $updateResult = (.\src\updater.ps1 -orgName ${{ github.repository_owner }} -PAT ${{ secrets.GITHUB_TOKEN }} -marketplaceRepo ${{ github.repository }} -userName "${{ secrets.username }}" -userEmail "${{ secrets.useremail }}" )
    
    - name: Upload json to this repository
      uses: LasyIsLazy/github-upload-action@v0.1.0
      with:
        access-token: ${{ secrets.PAT }}
        file-path: actions-data.json
        owner: ${{ github.repository_owner }}
        repo: ${{ github.repository }}
        #remote-dir:  // upload in the root
        branch-name: gh-pages